# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.cache/wt [current_project]
set_property parent.project_path D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  {c:/Users/MasterH/Documents/Tencent Files/958028260/FileRecv/wanchengban/wanchengban/HIT_74chips}
  {c:/Users/MasterH/Documents/Tencent Files/958028260/FileRecv/wanchengban/wanchengban/MY_74LS153}
  {c:/Users/MasterH/Documents/Tencent Files/958028260/FileRecv/wanchengban/wanchengban/MY_74LS194}
} [current_project]
set_property ip_output_repo d:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.srcs/sources_1/new/jicun.v
  D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.srcs/sources_1/new/erxuanyi.v
  D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.srcs/sources_1/new/huofei.v
  D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.srcs/sources_1/new/jishu.v
  D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.srcs/sources_1/new/da.v
  D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.srcs/sources_1/new/jishi.v
  D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.srcs/sources_1/new/bijiao.v
  D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.srcs/sources_1/new/check_g.v
  D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.srcs/sources_1/new/check_r.v
  D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.srcs/sources_1/new/pianxuan1.v
  D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.srcs/sources_1/new/pianxuan2.v
  D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.srcs/sources_1/new/led.v
  D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.srcs/sources_1/new/mima.v
  D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.srcs/sources_1/new/jishum.v
  D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.srcs/sources_1/new/xiaodou.v
  D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
}
add_files D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.srcs/constrs_1/new/yes.xdc
set_property used_in_implementation false [get_files D:/vivado/yanshiban_xiaodou/yanshiban/yanshiban/yanshiban.srcs/constrs_1/new/yes.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7a35tcsg324-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
