# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/yes.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_jicun_0_0/design_1_jicun_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_jicun_0_0 || ORIG_REF_NAME==design_1_jicun_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_erxuanyi_0_0/design_1_erxuanyi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_erxuanyi_0_0 || ORIG_REF_NAME==design_1_erxuanyi_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_huofei_0_0/design_1_huofei_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_huofei_0_0 || ORIG_REF_NAME==design_1_huofei_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_jishu_0_0/design_1_jishu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_jishu_0_0 || ORIG_REF_NAME==design_1_jishu_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_da_0_0/design_1_da_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_da_0_0 || ORIG_REF_NAME==design_1_da_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_huofei_0_1/design_1_huofei_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_huofei_0_1 || ORIG_REF_NAME==design_1_huofei_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_da_0_1/design_1_da_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_da_0_1 || ORIG_REF_NAME==design_1_da_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_jishi_0_0/design_1_jishi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_jishi_0_0 || ORIG_REF_NAME==design_1_jishi_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bijiao_0_0/design_1_bijiao_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_bijiao_0_0 || ORIG_REF_NAME==design_1_bijiao_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_check_g_0_0/design_1_check_g_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_check_g_0_0 || ORIG_REF_NAME==design_1_check_g_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_check_r_0_0/design_1_check_r_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_check_r_0_0 || ORIG_REF_NAME==design_1_check_r_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pianxuan1_0_0/design_1_pianxuan1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pianxuan1_0_0 || ORIG_REF_NAME==design_1_pianxuan1_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pianxuan2_0_0/design_1_pianxuan2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pianxuan2_0_0 || ORIG_REF_NAME==design_1_pianxuan2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_led_0_0/design_1_led_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_led_0_0 || ORIG_REF_NAME==design_1_led_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mima_0_0/design_1_mima_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mima_0_0 || ORIG_REF_NAME==design_1_mima_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_jishum_0_0/design_1_jishum_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_jishum_0_0 || ORIG_REF_NAME==design_1_jishum_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xiaodou_0_0/design_1_xiaodou_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xiaodou_0_0 || ORIG_REF_NAME==design_1_xiaodou_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xiaodou_0_1/design_1_xiaodou_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xiaodou_0_1 || ORIG_REF_NAME==design_1_xiaodou_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xiaodou_0_2/design_1_xiaodou_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xiaodou_0_2 || ORIG_REF_NAME==design_1_xiaodou_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xiaodou_2_0/design_1_xiaodou_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xiaodou_2_0 || ORIG_REF_NAME==design_1_xiaodou_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xiaodou_2_1/design_1_xiaodou_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xiaodou_2_1 || ORIG_REF_NAME==design_1_xiaodou_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xiaodou_4_0/design_1_xiaodou_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xiaodou_4_0 || ORIG_REF_NAME==design_1_xiaodou_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xiaodou_0_3/design_1_xiaodou_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xiaodou_0_3 || ORIG_REF_NAME==design_1_xiaodou_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xiaodou_0_4/design_1_xiaodou_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xiaodou_0_4 || ORIG_REF_NAME==design_1_xiaodou_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xiaodou_0_5/design_1_xiaodou_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xiaodou_0_5 || ORIG_REF_NAME==design_1_xiaodou_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xiaodou_0_6/design_1_xiaodou_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xiaodou_0_6 || ORIG_REF_NAME==design_1_xiaodou_0_6} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
